# Generated by Django 4.2.4 on 2023-08-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='group',
        ),
    ]
